### ISSUE TITLE
Few questions 

### ISSUE THREAD

**Issue by Pete9xi** [MarvinBeym/MscModApi#19]
Hi im not sure whats the best way to contact you, im already using the modapi by tommo and the mod is rather big code wise, im wondering if i can use this to effectively add bolts onto the current parts?

**Comment by MarvinBeym** [comment]
No, MscModApi replaces the ModApi by tommo

That was the main reason for remaking it.

Tommos implementation was very basic and required a lot of unnecessary steps to implement.
Adding screws added even more complexity.

My MscModApi bundles that, simplifies usage and adds more features.

If you want to remain with using tommo's part setup.

You will have to make your own screws implementation.

**Comment by Pete9xi** [comment]
No worries is there a guide on basic setup? i have a lot of logic that runs when the part is installed not sure how much of that would need to be rewritten for this api

**Comment by Pete9xi** [comment]
hello so i have started a re write i have been able to create the part and spawn it to the bench however when i go to place it on the car its not detecting the trigger bellow is my current code am i missing somthing?

`public override void OnLoad()
        {
            //load the asset bundle
            AssetsBD = Helper.LoadAssetBundle(this, "projectorheadlight.unity3d");
            projector = AssetsBD.LoadAsset("HeadLightLeftv5.prefab") as GameObject;
            GameObject parent = GameObject.Find("MiscParts");
            partBaseInfo = new PartBaseInfo(this, AssetsBD, partsList);

            ProjectorLeft = new Part("ProjectorLeft",
                "ProjectorLeft", parent,
                ProjectorLeft_installLocation, new Vector3(270, 1.366038E-05f, 0), partBaseInfo,false,true, "HeadLightLeftv5.prefab");
           ProjectorLeft.AddScrews(
                new[]
                {
                    new Screw(new Vector3(0f, 0.04f, -0.0030f), new Vector3(0, 180, 0)),
                    new Screw(new Vector3(0f, -0.04f, -0.0030f), new Vector3(0, 180, 0)),
                }, 0.6f, 8);
            AssetsBD.Unload(false);
            ProjectorLeft.SetDefaultPosition(new Vector3(-14.30006f, 0.5413833f, -0.1148765f));
            ProjectorLeft.ResetToDefault();


        }`

**Comment by Pete9xi** [comment]
![image](https://github.com/MarvinBeym/MscModApi/assets/3973221/3d96e0e6-cb95-4615-9841-afd417534fd8)
`MSCLoader.ModConsole.Log("Entered the trigger.");
			MSCLoader.ModConsole.Log("If statment...");
			MSCLoader.ModConsole.Log("part.uninstallWhenParentUninstalls: " + part.uninstallWhenParentUninstalls);
			MSCLoader.ModConsole.Log("part.ParentInstalled(): " + part.ParentInstalled());
			MSCLoader.ModConsole.Log("!collider.gameObject.IsHolding(): " + collider.gameObject.IsHolding());
			MSCLoader.ModConsole.Log("collider.gameObject != part.gameObject: " + collider.gameObject +  " " + !part.gameObject);
			MSCLoader.ModConsole.Log("part.IsInstallBlocked(): " + part.IsInstallBlocked());`

**Comment by MarvinBeym** [comment]
Sorry for the late reply, I didn't get a notification to your older comments.

can you ModConsole.Log what collider.gameobject & part.gameObject is
Should be something like
`MSCLoader.ModConsole.Log("collider: " + collider.gameObject.name + ", part: " + part.gameObject.name);`

**Comment by MarvinBeym** [comment]
Or alternatively enable the "uninstallWhenparentUninstalls" flag?

There may be a bug in that line

**Comment by Pete9xi** [comment]
No worries, is that in the mscmodapi source or my mod source?

**Comment by MarvinBeym** [comment]
> No worries, is that in the mscmodapi source or my mod source?

if you mean enabling "uninstallWhenParentUninstalls" that's a flag when you create the part with new Part(...)

In your case you have it set to false right after you pass "partBaseInfo"

```
ProjectorLeft = new Part("ProjectorLeft",
            "ProjectorLeft", parent,
            ProjectorLeft_installLocation, 
            new Vector3(270, 1.366038E-05f, 0), 
            partBaseInfo,
            false, <--------------------------------------------
            true, 
            "HeadLightLeftv5.prefab"
);
```

**Comment by MarvinBeym** [comment]
generally, it's "recommended" to enable it, you generally don't want the part to remain on the parent, if the parent is removed from the car.

**Comment by Pete9xi** [comment]
ummmm well it let me install it and the car flew away 
![image](https://github.com/MarvinBeym/MscModApi/assets/3973221/9fea98a3-199f-41e6-845e-0a46f9d73501)

**Comment by Pete9xi** [comment]
very odd possibly due to the rotation maybe
![image](https://github.com/MarvinBeym/MscModApi/assets/3973221/217b93db-4768-48c5-a1c8-9193fcb61921)

**Comment by MarvinBeym** [comment]
Likely a collider issue on your object.

What does your object setup in unity look like (RigidBody, Collider, ...)

**Comment by Pete9xi** [comment]
yeah it has a rigid body and a collider does your api add these? i know they were required for the old parts api by tommo

**Comment by MarvinBeym** [comment]
If you have the modder toolkit mod (or whatever it's called) installed you could enable the debug view of the collider (and check it gets actually disabled by the mscModApi on install)

**Comment by Pete9xi** [comment]
i have the devtool kit but its not the other one which requires MSCLoaderPro

**Comment by MarvinBeym** [comment]
> If you have the modder toolkit mod (or whatever it's called) installed you could enable the debug view of the collider (and check it gets actually disabled by the mscModApi on install)

Nexus Mods
https://www.nexusmods.com › mods
Developer Toolset II - My Summer Car

**Comment by Pete9xi** [comment]
Yeah that one requires mod loader pro which im not using

**Comment by Pete9xi** [comment]
> > If you have the modder toolkit mod (or whatever it's called) installed you could enable the debug view of the collider (and check it gets actually disabled by the mscModApi on install)
> 
> Nexus Mods https://www.nexusmods.com › mods Developer Toolset II - My Summer Car

my bad i had forgotten i disabled `disableCollisionswheninstalled`

**Comment by Pete9xi** [comment]
just need to figure out why the bolts are not being detected next

**Comment by MarvinBeym** [comment]
> Yeah that one requires mod loader pro which im not using

No it doesn't

**Comment by MarvinBeym** [comment]
(or rather you don't need it)

**Comment by Pete9xi** [comment]
> 

oh intresting ill download it but i have resolved the collider issue working on the screws now

**Comment by MarvinBeym** [comment]
Let me know if you need more help with the screws

... The implementation "should" work flawlessly

At least I never had trouble....

**Comment by Pete9xi** [comment]
okay so its adding the screws 
`ProjectorLeft.AddScrews(
                new[]
                {
                    new Screw(new Vector3(-0.09532297f, 0.01886879f, 0.003658213f), new Vector3(270f, -1.575302E-06f, 0)),
                    new Screw(new Vector3(0.09062467f, 0.01886861f, 0.003657319f), new Vector3(270f, -3.990142E-06f, 0)),
                }, 0.6f, 8);`
                
they should be size 8 but no matter what spanner you hold in tool mode it doesnt detect the screw

**Comment by Pete9xi** [comment]
somthing strange is happening it will detect the screws when i use the dll from the source code which is v 1.0.5? were you working on any bugs after 1.0.4?

**Comment by Pete9xi** [comment]
![image](https://github.com/MarvinBeym/MscModApi/assets/3973221/0dce9359-198f-4b9a-bd20-147dd1912746)

**Comment by MarvinBeym** [comment]
Possible, i'll check that later today

**Comment by Pete9xi** [comment]
> Possible, i'll check that later today

No worries unless its the debug setting that is causing it as when i use v1.0.5 it has the option to force install etc?

**Comment by MarvinBeym** [comment]
> > Possible, i'll check that later today
> 
> No worries unless its the debug setting that is causing it as when i use v1.0.5 it has the option to force install etc?

Force install is only available when you compile the MSCModApi in debug mode yourself.

The release version doesn't have that.

Don't want users cheating, the instalaltion is part of the experience ;)

**Comment by Pete9xi** [comment]
> > > Possible, i'll check that later today
> > 
> > 
> > No worries unless its the debug setting that is causing it as when i use v1.0.5 it has the option to force install etc?
> 
> Force install is only available when you compile the MSCModApi in debug mode yourself.
> 
> The release version doesn't have that.
> 
> Don't want users cheating, the instalaltion is part of the experience ;)

I rebuilt the source as a release and the bolts get detected  everything seems to be okay so far so there is something in 1.0.4 that is not happy not sure what it could be i havent checked the commit history yet

**Comment by Pete9xi** [comment]
looking over the commit history some small changes were made to part.cs mainly the setup void, and there was a change to the isfixed bool but dont see how that would effect the screw detection

**Comment by MarvinBeym** [comment]
I did have quite some changes uncommited.

I did a quick release +fixed the one you found that prevented installing the part when "uninstallWithParent..." was disabled

could have bugs, I'm unsure how far I was when I made those changes.

https://github.com/MarvinBeym/MscModApi/releases/tag/1.1.0

**Comment by MarvinBeym** [comment]
I'll think about getting back to working on my own mods to verify everything works like it's supposed to

**Comment by Pete9xi** [comment]
i tend to do that to people lol, took on another project and raised it from archived state for the owner to come back and say hey lets team up, it takes up so much time though i have been meaning to rewrite my mod for a while just never had the motivation todo it but it makes a nice break from my other projects

**Comment by Pete9xi** [comment]
need to investigate the shop system as well as before i did it manually which was not smooth when it comes to opening the box the lamp hovered lol

**Comment by MarvinBeym** [comment]
> need to investigate the shop system as well as before i did it manually which was not smooth when it comes to opening the box the lamp hovered lol

the update I did also features "kits" and "boxes"

where a kit contains different kinds of parts (like headlamp, lightbulb, glass, wires, ...)

and a box contains x copies of the same part (like a pack of 2 lighbulbs)

most of the code is tested (because the code was extracted from my Turbo & Ecu mod)

but with further improvements they could have problems I haven't experienced yet, so let me know if you find something)

**Comment by Pete9xi** [comment]
> > well i have basic function of the lights and the checks for power and the dash control i have managed to slice down big time, now i just need to implement the lamps and the wear system which im hoping i can improve as it was janky before
> 
> "Wear" system may also come to the MscModApi "a BIG MAYBE" though
> 
> I had wear implemented for my Turbo mod, so that would be another thing I would extract from that and move to the MscModAPI for everyone to use.

Yeah its not a big thing the lamps had random ints that where effectively hours when the headlights are on the counter starts and that reduces the time left a lamp could fail at anytime these values were saved to a file and pulled back in when reloaded so i could just reuse those scripts

**Comment by Pete9xi** [comment]
> > need to investigate the shop system as well as before i did it manually which was not smooth when it comes to opening the box the lamp hovered lol
> 
> the update I did also features "kits" and "boxes"
> 
> where a kit contains different kinds of parts (like headlamp, lightbulb, glass, wires, ...)
> 
> and a box contains x copies of the same part (like a pack of 2 lighbulbs)
> 
> most of the code is tested (because the code was extracted from my Turbo & Ecu mod)
> 
> but with further improvements they could have problems I haven't experienced yet, so let me know if you find something)

Does this add a box gameobject on the shelf in the store? Or is this it the parts catalogue?

**Comment by MarvinBeym** [comment]
*The MscModApi Shop is the brown "sign" in Taimbos & Fleetaris shop

**Comment by Pete9xi** [comment]
> repo is open to pull requests if you want to add that as a feature :)

i may do lol, another question not sure if you have discord or something but ill post it here, with the parts in my old build i have 4 game objects Bulb1-4 Bulb1 and 3 were for the left light and 2-4 for the right it was very annoying is there a way to say have a part that is replaceable but still be able to reference it by name ie leftBulb rightBulb that way i can still create a wear system so when on breaks it can just spawn a new one that will go into that side if that makes sense?

**Comment by MarvinBeym** [comment]
Discord: `donnerplays`

Are all bulbs different gameobjects?
or is Bulb1 the same as Bulb3 and Bulb2 the same as Bulb4?

if that's the case you could use the **Box** Feature.

You'd create 2 boxes 1 that can be either Bulb1 or Bulb3
and one that is either Bulb2 or Bulb4

you can then allow buying infinite boxes of those. through the Shop system.

Players can then install multiple of those bulbs (which you likely don't want)
to avoid this, you then add custom code that blocks installing another bulb if the same type is already installed
(you can register events on a part, the method (Action) you pass to that method then get's called
Examples:
- AddPreInstallAction (before the part is put on the parent (right after you click "install")
- AddPostInstallAction (right after the part is "popped" off the parent)
(There are more options on the part object)

that way you can then realise a chain
-AddPostInstallAction  
=> find all bulb parts (maybe add them to a list when they are spawned) 
=> set their install to blocked (part.BlockInstall(true/false);
- AddPostUninstallAction
=> find all bulb parts
=> remove the block from all parts again

**Comment by Pete9xi** [comment]
They are the same 3d Model it was just a way for me to keep one set active and one set hidden that would be teleported when purchased that way if bulb 1 was dead bulb three would be TPed to the shop when you open a box, it would be nice to have one part that could be attached to either ProjectorLeft or ProjectorRight then once its installed the values could be set as you said via PostInstallAction
