### ISSUE TITLE
Newest update breaks DonnerTechRacing Turbocharger

### ISSUE THREAD

**Issue by MOOOOs** [MarvinBeym/MscModApi#46]
after updating it will no longer work and game will tell on launch that 
![image](https://github.com/user-attachments/assets/594ac690-41ae-47a3-bd31-f88fc1b91475)

**Comment by MarvinBeym** [comment]
Who told you the Turbo mod was compatible with this version of MscModApi?

**Comment by MOOOOs** [comment]
then why mod loader offer me to update it?

**Comment by MarvinBeym** [comment]
because MscModApi was updated

doesn't mean all mods using it are compatible (yet).

**Comment by MOOOOs** [comment]
ah ok then gonna lower version then
