### ISSUE TITLE
i dont have assets or .dll

### ISSUE THREAD

**Issue by eliasFI** [MarvinBeym/MscModApi#7]

**Comment by eliasFI** [comment]
![dadadadadada](https://user-images.githubusercontent.com/93454529/139560755-422d7dfc-98a7-4e73-a166-d73fb05ceeb7.PNG)

**Comment by MarvinBeym** [comment]
Because you downloaded the source code instead of the compiled version
![2021-10-31_08-11](https://user-images.githubusercontent.com/19359112/139572500-b1aadde2-464f-4dc8-b862-ea35dce2cf78.png)
.
