### ISSUE TITLE
MscModApi.xml is missing in the .RAR archive 

### ISSUE THREAD

**Issue by JustGuren** [MarvinBeym/MscModApi#9]
![image](https://user-images.githubusercontent.com/93497150/139605955-488fc768-1a8b-4b38-8122-fddbce08a23c.png)

**Comment by MarvinBeym** [comment]
I haven't worked on code documentation yet.

Might do that today.

**Comment by MarvinBeym** [comment]
API documentation is now available here:
https://marvinbeym.github.io/MscModApi/#/

Documentation in code (MscModApi.xml) will come later.

**Comment by carl1055** [comment]
Marvin dude i cant find the frickin .xml file DUDE
